version: '3.8'

services:
  app:
    build:
      context: ./backend/docker/8.2
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    container_name: spincash
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: 'debug'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      DB_CONNECTION: 'pgsql'
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
    volumes:
      - ./backend:/var/www/html:cached
    env_file: ./backend/.env
    depends_on:
      - db
      - redis

  db:
    env_file: ./backend/.env
    image: postgres:latest
    container_name: spincash_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backend/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    env_file: ./backend/.env
    image: redis:alpine
    container_name: spincash_redis
    volumes:
      - ./backend/redis:/data
    ports:
      - "6379:6379"

  centrifugo:
    env_file: ./backend/.env
    image: centrifugo/centrifugo:v3
    container_name: spincash_centrifugo
    command: centrifugo
    environment:
      - CENTRIFUGO_SECRET=${CENTRIFUGO_SECRET}
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_SECRET}
      - CENTRIFUGO_ADMIN=false
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
    ports:
      - "8001:8001"

  adminer:
    image: adminer
    container_name: spincash_adminer
    restart: unless-stopped
    ports:
      - "1337:8080"