version: '3.8'

services:
  app:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: ./docker/app/Dockerfile
      target: development
    container_name: spincash
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./backend/docker/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
    ports:
      - "8000:8000"
      - "9003:9003"
    depends_on:
      - db
      - redis


  centrifugo:
    image: centrifugo/centrifugo:v3
    environment:
      - CENTRIFUGO_SECRET=${CENTRIFUGO_SECRET}
      - CENTRIFUGO_TOKEN_HMAC_SECRET_KEY=${CENTRIFUGO_TOKEN_SECRET}
      - CENTRIFUGO_ADMIN_PASSWORD=${CENTRIFUGO_ADMIN_PASSWORD}
      - CENTRIFUGO_ADMIN_SECRET=${CENTRIFUGO_ADMIN_SECRET}
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
      - CENTRIFUGO_ADMIN=true
